accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    # User Authentication
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.password_update, name='password_update'),
    # User Profile
    path('<username>/', views.profile, name='profile'),
    path('<username>/follow/', views.follow, name='follow'),
]

instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from . import views
from django.urls import path

app_name = 'posts'
urlpatterns = [
    # posts
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('<int:post_pk>/delete', views.delete, name='delete'),
    path('<int:post_pk>/update', views.update, name='update'),
    # comments
    path('<int:post_pk>/create_comment/', views.create_comment, name='create_comment'),
    path('<int:post_pk>/delete/<int:comment_pk>', views.delete_comment, name='delete_comment'),
    # like
    path('<int:post_pk>/like/<str:before>/', views.like, name='like'),
    # Search
    path('search/', views.search, name='search'),
    path('click_tag/<str:hashtag>', views.click_tag, name='click_tag'),
    # Close
    # path('<int:post_pk>/close/<str:next>/', views.close, name='close'),
]

posts/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.
class Tag(models.Model):
    content = models.CharField(max_length=10, unique=True)


class Post(models.Model):
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    photo = ProcessedImageField(
        # upload_to="media/%Y/%m/%d",
        format = 'JPEG',
        processors = [ResizeToFill(633, 633)],
        options = {'quality': 90},
    )
    content = models.TextField()
    hashtags = models.ManyToManyField(Tag, related_name='taged_posts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

posts/forms.py
from django import forms
from .models import Post, Comment, Tag

class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ('photo', 'content',)


class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ('content',)


class TagForm(forms.ModelForm):

    class Meta:
        model = Tag
        fields = '__all__'  

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404, resolve_url
from .models import Post, Comment, Tag
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST
from .forms import PostForm, CommentForm, TagForm
from accounts.models import User
from django.db.models import Count


# Create your views here.
@login_required
def index(request):
    posts = Post.objects.all().order_by('-created_at')
    followings = request.user.followings.all()
    users = User.objects.all().distinct()
    context = {
        'posts': posts,
        'followings': followings,
        'users': users,
    }
    return render(request, 'posts/index.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method=='POST':
        post_form = PostForm(request.POST, request.FILES)
        if post_form.is_valid():
            post = post_form.save(commit=False)
            post.user = request.user
            post.save()

            content = post.content.split()
            content_new = ''
            for word in content:
                if word[0]=='#':
                    if {'content': word} in Tag.objects.all().values('content'):
                        tag = Tag.objects.get(content=word)
                        post.hashtags.add(tag)                
                    else:
                        tag = Tag.objects.create(content=word)
                        post.hashtags.add(tag)                
                else:
                    content_new += word + ' '
            post.content = content_new
            post.save()

            return redirect('posts:detail', post.pk)
    else:
        post_form = PostForm()
    context = {
        'post_form': post_form,
    }
    return render(request, 'posts/create.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def detail(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    comments = post.comment_set.all()
    form = CommentForm()
    content = post.content.split()
    context = {
        'form': form,
        'post': post,
        'comments': comments,
    }
    return render(request, 'posts/detail.html', context)


@require_POST
def delete(request, post_pk):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    
    post = get_object_or_404(Post, pk=post_pk)
    if post.user==request.user:
        post.delete()
        return redirect('posts:index')
    return redirect('posts:detail', post_pk)


@login_required
@require_http_methods(['GET', 'POST'])
def update(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    if request.method=='POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        post = form.save(commit=False)
        post.user = request.user
        post.save()
        return redirect('posts:detail', post_pk)
    else:
        form = PostForm(instance=post)
    context = {
        'form': form,
    }
    return render(request, 'posts/update.html', context)


# Comments -----------------------------------------
@require_POST
def create_comment(request, post_pk):
    if not request.user.is_authenticated:
        return redirect('accounts:login')

    post = get_object_or_404(Post, pk=post_pk)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.post = post
        comment.save()
    return redirect('posts:detail', post_pk)


@require_POST
def delete_comment(request, post_pk, comment_pk):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    
    post = get_object_or_404(Post, pk=post_pk)
    comment = post.comment_set.get(pk=comment_pk)
    comment.delete()
    return redirect('posts:detail', post_pk)


# Like ---------------------------------
@require_POST
def like(request, post_pk, before):
    if not request.user.is_authenticated:
        return redirect('accounts:login')

    post = get_object_or_404(Post, pk=post_pk)
    if post.like_users.filter(username=request.user).exists():
        post.like_users.remove(request.user)
    else:
        post.like_users.add(request.user)
    
    if before=='detail':
        return redirect('posts:detail', post_pk)
    else:
        next_url = resolve_url('posts:index')
        return redirect(f'{next_url}#{before}')


# Search ------------------------------
@login_required
@require_http_methods(['GET', 'POST'])
def search(request):
    search = request.GET.get('search')
    if search[0]=='#' and Tag.objects.filter(content=search).exists():
        tag = Tag.objects.get(content=search)
        posts = tag.taged_posts.all()
        context = {
            'hashtag': search,
            'posts': posts,
        }
        return render(request, 'posts/search_result.html', context)
    elif User.objects.filter(username=search).exists():
        return redirect('accounts:profile', search)
    else:
        return render(request, 'posts/not_found.html')


@login_required
@require_http_methods(['GET', 'POST'])
def click_tag(request, hashtag):
    if Tag.objects.filter(content=hashtag).exists():
        tag = Tag.objects.get(content=hashtag)
        posts = tag.taged_posts.all()
        context = {
            'hashtag': hashtag,
            'posts': posts,
        }
        return render(request, 'posts/search_result.html', context)
    else:
        return render(request, 'posts/not_found.html')


# Close ------------------------------
# @login_required
# @require_http_methods(['GET', 'POST'])
# def close(request, post_pk, before):
#     if before=='index':
#         next_url = resolve_url('posts:index')
#         return redirect(f'{next_url}#{post_pk}')
#     else:
#         next_url = resolve_url('accounts:profile', before)
#         return redirect(f'{next_url}#{post_pk}')

posts/templates/posts/details/_content.html
{% load static %}

<div class="d-flex flex-row align-items-start">

  <!-- start 작성자 프로필사진 & ID -->
  <div class="col-1 pl-0 pt-1 d-none d-md-block">
    <a href="{% url 'accounts:profile' post.user %}">
      {% if post.user.profile_image %}
        <img src="{{ post.user.profile_image.url }}" alt="{{ post.user.profile_image }}" style="border-radius: 50%; width: 35px;">
      {% else %}
        <img src="{% static 'none_profile.jpg' %}" style="border-radius: 50%; width: 35px;">
      {% endif %}
    </a>
  </div>
  <!-- end -->
    
  <!-- start 게시글 내용 & 해쉬태그 & 작성일 -->
  <div class="col pl-2 ml-2 d-none d-md-block">

    <p class="mb-1">
      <a class="text-decoration-none" href="{% url 'accounts:profile' post.user %}"><b class="mr-1 my-0 text-dark">{{ post.user }}</b></a>
      {% for word in post.content.split %}
        {{ word }}
      {% endfor %}
      
      <br>

      {% for tag in post.hashtags.all %}
        <a href="{% url 'posts:click_tag' tag.content %}">{{ tag.content }}</a>
      {% endfor %}
    </p>

    <p class="text-black-50" style="font-size: small;">{{ post.created_at|date:'m월 d일' }}</p>
  
  </div>
  <!-- end-->

</div>

posts/templates/posts/details/_footer.html
{% load static %}
{% load custom_filter %}

{% if comments %}
  <!-- 댓글 작성자 정보 & 내용 -->
  <div class="d-none d-md-block" style="overflow:auto; height: 150px;">

  {% for comment in comments %}
    <div class="d-flex align-items-start mb-0">
      
      <div class="col-1 pl-0 pt-1">
        <a href="{% url 'accounts:profile' comment.user %}">
          {% if comment.user.profile_image %}
            <img src="{{ comment.user.profile_image.url }}" alt="{{ comment.user.profile_image }}" style="border-radius: 50%; width: 35px;">
          {% else %}
            <img src="{% static 'none_profile.jpg' %}" style="border-radius: 50%; width: 35px;">
          {% endif %}
        </a>
      </div>
      
      <div class="col ml-3 h-auto">
        <div class="row pb-0">
          <p class="mr-3 mb-1">
            <a href="{% url 'accounts:profile' comment.user %}" class="text-dark text-decoration-none"><b>{{ comment.user }}</b></a> {{ comment.content }}
          </p>
        </div>
        <div class="row">
          <p class="text-black-50 mt-0 pt-0" style="font-size: small">{{ comment.created_at|processed_timesince }} 전</p>
          {% if request.user == comment.user %}
            <form action="{% url 'posts:delete_comment' post.pk comment.pk %}" method="POST">
              {% csrf_token %}
              <button class="text-danger border-0 bg-white pl-2 ml-2">삭제</button>
            </form>
          {% endif %}
        </div>
      </div>
      
    </div>
  {% endfor %}
  </div>

{% else %}
  <p>아직 작성된 댓글이 없습니다.</p>

{% endif %}
<hr class="my-2 d-none d-md-block">
  
<!-- 좋아요 관련 -->
<form action="{% url 'posts:like' post.pk 'detail' %}" data-post-id="{{ post.pk }}" data-username="{{ request.user }}" method="POST" id='like-form'>
  {% csrf_token %}
  {% if request.user in post.like_users.all %}
    <button class="fas fa-heart fa-2x border-0 bg-white"></button>
  {% else %}
    <button class="far fa-heart fa-2x border-0 bg-white"></button>
  {% endif %}

  <i class="far fa-comment fa-2x ml-2"></i>

  <i class="far fa-paper-plane fa-2x ml-2"></i>
</form>
<p class="ml-1 mt-1 mb-0"><b>좋아요 {{ post.like_users.all.count }}개</b></p>
<hr class="my-2">  

<!-- 댓글 작성 -->
<form action="{% url 'posts:create_comment' post.pk %}" method="POST">
  {% csrf_token %}
  {{ form }}
  <button class="border-0 bg-white text-primary"><b>게시</b></button>
</form>

posts/templates/posts/details/_header.html
{% load static %}

<div class="d-flex flex-row align-items-center">

  <!-- start 작성자 프로필사진 -->
  <a href="{% url 'accounts:profile' post.user %}">
  {% if post.user.profile_image %}
    <img src="{{ post.user.profile_image.url }}" alt="{{ post.user.profile_image }}" style="border-radius: 50%; width: 35px;">
  {% else %}
    <img src="{% static 'none_profile.jpg' %}" style="border-radius: 50%; width: 35px;">
  {% endif %}
  </a>
  <!-- end -->

  <!-- start 작성자 ID 및 팔로우 버튼 -->
  <div class="d-flex flex-row align-items-baseline">
    
    <h5 class="ml-3"><a href="{% url 'accounts:profile' post.user %}" class="text-dark text-decoration-none">{{ post.user }}</a></h5>
    
    <form action="{% url 'accounts:follow' post.user %}" method="POST" id="follow-form" data-username="{{ post.user }}">
      {% csrf_token %}
      {% if request.user != post.user %}
        {% if request.user not in post.user.followers.all %}
          <button class="btn btn-toolbar text-primary m-0"><b>팔로우</b></button>
        {% else %}
          <button class="btn btn-toolbar text-primary m-0"><b>팔로우 취소</b></button>
        {% endif %}
      {% endif %}
    </form>
    
  </div>
  <!-- end -->
  
    <button class="border-0 bg-white ml-auto mr-3"><a href="../#{{post.pk}}"><i class="fas fa-times fa-2x" style="color: black"></i></a></button>
  
</div>