accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    # User Authentication
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.password_update, name='password_update'),
    # User Profile
    path('<username>/', views.profile, name='profile'),
    path('<username>/follow/', views.follow, name='follow'),
]

instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from . import views
from django.urls import path

app_name = 'posts'
urlpatterns = [
    # posts
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('<int:post_pk>/delete', views.delete, name='delete'),
    path('<int:post_pk>/update', views.update, name='update'),
    # comments
    path('<int:post_pk>/create_comment/', views.create_comment, name='create_comment'),
    path('<int:post_pk>/delete/<int:comment_pk>', views.delete_comment, name='delete_comment'),
    # like
    path('<int:post_pk>/like/<str:before>/', views.like, name='like'),
    # Search
    path('search/', views.search, name='search'),
    path('click_tag/<str:hashtag>', views.click_tag, name='click_tag'),
    # Close
    # path('<int:post_pk>/close/<str:next>/', views.close, name='close'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')
    profile_image = ProcessedImageField(
        blank = True,
        format = 'JPEG',
        processors = [Thumbnail(200, 200)],
        options = {'quality': 90},
    )
    introduction = models.TextField(blank=True)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    
    class Meta:
        model = get_user_model()
        fields = UserCreationForm.Meta.fields


class CustomUserChangeForm(UserChangeForm):
    password = None
    
    class Meta:
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name', 'profile_image', 'introduction')

accounts/views.py
from .models import User
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_GET, require_http_methods
from django.http import JsonResponse

# User Authentication -------------------------------
@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.method=='POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('posts:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@require_http_methods(['GET', 'POST'])
def login(request):
    if request.method=='POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            next_url = request.GET.get('next')
            return redirect(next_url or 'posts:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
        return redirect('posts:index')
    
    return redirect('accounts:login')


@login_required
@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method=='POST':
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            user = form.save()
            return redirect('accounts:profile', user)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def delete(request):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    
    if request.method=='POST':
        request.user.delete()
        return redirect('posts:index')
    
    return render(request, 'accounts/delete.html')
    

@login_required
@require_http_methods(['GET', 'POST'])
def password_update(request):
    if not request.user.is_authenticated:
        return redirect('accounts:login')

    if request.method=='POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            auth_login(request, request.user)
            return redirect('accounts:update')
    else:       
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/password_update.html', context)


# User Profile ----------------------------------
@login_required
@require_http_methods(['GET', 'POST'])
def profile(request, username):
    person = get_object_or_404(User, username=username)
    context ={
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)


@require_POST
def follow(request, username):
    if not request.user.is_authenticated:
        return redirect('accounts:login')

    person = get_object_or_404(User, username=username)
    me = request.user
    if person!=me:
        if person.followers.filter(pk=me.pk).exists():
            person.followers.remove(me)
            isFollowed = False
        else:
            person.followers.add(me)
            isFollowed = True
        data = {
            'isFollowed': isFollowed,
        }
    return JsonResponse(data)

accounts/templates/accounts/delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>회원 탈퇴하기</h1>
  <hr>
  <h4>정말로 탈퇴하시겠습니까?</h4>
  <p>- 회원 정보는 모두 삭제됩니다.</p>
  <form action="{% url 'accounts:delete' %}" method="POST">
    {% csrf_token %}
    <button class="btn btn-danger">네, 탈퇴하겠습니다.</button>
    <a href="{% url 'accounts:update' %}" class="btn btn-dark">아니요 (회원정보수정 페이지로 돌아갑니다)</a>
  </form>
  <hr>

{% endblock  %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center">로그인 화면</h1>
  <hr>

  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-dark">로그인</button>
    <a class="btn btn-dark" href="">취소</a>
  </form>

{% endblock  %}

accounts/templates/accounts/not_found_user.html
{% extends 'base.html' %}

{% block content %}
  <div class="jumbotron bg-light">
    <h3>검색결과를 찾을 수 없어요. ㅠㅠ</h3>
    </div>
  
{% endblock  %}

accounts/templates/accounts/password_update.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center">비밀번호변경 화면</h1>
  <hr>

  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-dark">변경하기</button>
    <a class="btn btn-dark" href="{% url 'posts:index' %}">취소</a>
  </form>
  <hr>

{% endblock  %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}

  <!-- 프로필 화면의 유저 정보 -->
  {% include 'accounts/profiles/_profile_info.html' %}
  <hr class="my-4">

  <!-- 게시글 쓰기 -->
  <a class="text-center" href="{% url 'posts:create' %}">게시글 쓰기</a>
  <!-- 프로필 화면의 유저 게시글 목록 -->
  {% include 'accounts/profiles/_profile_posts.html' %}
  
  <script>
    const followForm = document.querySelector('#follow-form');
    const csrfToken = document.querySelector('input[name=csrfmiddlewaretoken]').value;
    const config = { headers: {'X-CSRFToken': csrfToken}};

    const followBtn = followForm.querySelector('button');
    const username = followForm.dataset.username;
    const API_URL = `/accounts/${username}/follow/`;
    
    function follow(e) {
      e.preventDefault();
      axios.post(API_URL, {}, config)
        .then(response => {
          const { isFollowed } = response.data;
          followBtn.innerText = isFollowed ? '팔로우 취소' : '팔로우';
          followBtn.classList.toggle('btn-primary');
          followBtn.classList.toggle('btn-toolbar');
          followBtn.classList.toggle('btn-secondary');
        })
        .catch(err => {
          console.error(err);
        })
      };

    followForm.addEventListener('submit', follow);
  </script>

{% endblock  %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center">회원가입 화면</h1>
  <hr>

  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-dark">회원가입</button>
    <a class="btn btn-dark" href="">취소</a>
  </form>

{% endblock  %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center">회원정보수정 화면</h1>
  <hr>

  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-dark">수정하기</button>
    <a class="btn btn-dark" href="{% url 'posts:index' %}">취소</a>
  </form>
  <hr>
  <a class="mr-3" href="{% url 'accounts:password_update' %}">비밀번호 변경하기</a>
  <a href="{% url 'accounts:delete' %}">회원 탈퇴하기</a>
  <hr>

{% endblock  %}