accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    # User Authentication
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.password_update, name='password_update'),
    # User Profile
    path('<username>/', views.profile, name='profile'),
    path('<username>/follow/', views.follow, name='follow'),
]

instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from . import views
from django.urls import path

app_name = 'posts'
urlpatterns = [
    # posts
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('<int:post_pk>/delete', views.delete, name='delete'),
    path('<int:post_pk>/update', views.update, name='update'),
    # comments
    path('<int:post_pk>/create_comment/', views.create_comment, name='create_comment'),
    path('<int:post_pk>/delete/<int:comment_pk>', views.delete_comment, name='delete_comment'),
    # like
    path('<int:post_pk>/like/<str:before>/', views.like, name='like'),
    # Search
    path('search/', views.search, name='search'),
    path('click_tag/<str:hashtag>', views.click_tag, name='click_tag'),
    # Close
    # path('<int:post_pk>/close/<str:next>/', views.close, name='close'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/1b216d2a26.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <title>Instagram</title>
</head>
<body class="bg-light">
  <!-- Start Navbar -->
  <nav class="navbar navbar-expand navbar-light bg-white align-items-baseline border-bottom justify-content-center sticky-top" >
    
    <div class="collapse navbar-collapse align-items-baseline justify-content-xl-around justify-content-between" id="navbarSupportedContent">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'logo_nav.jpg' %}">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <form class="form-inline my-2 my-lg-0 d-none d-sm-inline" action="{% url 'posts:search' %}" method="GET">
        <input class="form-control mr-sm-2 bg-light" type="search" placeholder="검색" aria-label="Search" name="search">
      </form>

      <ul class="navbar-nav align-items-baseline">
        {% if user.is_authenticated %}
          <li class="nav-item active">
            {% if request.META.PATH_INFO == '/posts/' %}
              <a class="nav-link pl-5 ml-5" href="{% url 'posts:index' %}"><img src="{% static 'home_nav_active.jpg' %}"></a>
            {% else %}
              <a class="nav-link" href="{% url 'posts:index' %}"><img src="{% static 'home_nav.jpg' %}"></a>
            {% endif %}
          </li>

          <li class="nav-item active">
            <a class="nav-link pl-1" href="#"><img src="{% static 'dm_nav.jpg' %}"></a>
          </li>

          <li class="nav-item active">
            <a class="nav-link" href="#"><img src="{% static 'like_nav.jpg' %}"></a>
          </li>

          <li class="nav-item active">
            <div class="dropdown">  
              <button class="border-0 bg-white dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% if request.user.profile_image %}
                  <img src="{{ request.user.profile_image.url }}" alt="{{ request.user.profile_image }}" class="border" style="border-radius: 50%; width: 28px;">
                {% else %}
                  <img src="{% static 'profile_nav.jpg' %}">
                {% endif %}
              </button>

              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item pl-2 ml-1" href="{% url 'accounts:profile' request.user %}"><i class="far fa-user-circle mr-2"></i>프로필</a>
                <a class="dropdown-item pl-2 ml-1" href="{% url 'accounts:update' %}"><i class="fas fa-cog mr-2"></i>설정</a>
                <hr class="my-2">
                <form class="nav-link" action="{% url 'accounts:logout' %}" method="POST">
                  {% csrf_token %}
                  <button class="border-0 bg-transparent">로그아웃</button>
                </form>
              </div>
            </div>
          </li>

        {% else %}
          <li class="nav-item active">
            <a class="nav-link btn btn-primary text-white mr-2" href="{% url 'accounts:login' %}"><b>로그인</b></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link text-primary" href="{% url 'accounts:signup' %}"><b>회원가입</b></a>
          </li>

        {% endif %}
      </ul>
    </div>
  </nav>
  <!-- End Navbar -->


  {% comment %} <h1 class="text-center">Instagram</h1>
  <hr> {% endcomment %}

  <div class="container-lg section-md" >
    {% block content %}
    {% endblock  %}
  </div>

  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>