accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    # User Authentication
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.password_update, name='password_update'),
    # User Profile
    path('<username>/', views.profile, name='profile'),
    path('<username>/follow/', views.follow, name='follow'),
]

instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from . import views
from django.urls import path

app_name = 'posts'
urlpatterns = [
    # posts
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('<int:post_pk>/delete', views.delete, name='delete'),
    path('<int:post_pk>/update', views.update, name='update'),
    # comments
    path('<int:post_pk>/create_comment/', views.create_comment, name='create_comment'),
    path('<int:post_pk>/delete/<int:comment_pk>', views.delete_comment, name='delete_comment'),
    # like
    path('<int:post_pk>/like/<str:before>/', views.like, name='like'),
    # Search
    path('search/', views.search, name='search'),
    path('click_tag/<str:hashtag>', views.click_tag, name='click_tag'),
    # Close
    # path('<int:post_pk>/close/<str:next>/', views.close, name='close'),
]

posts/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.
class Tag(models.Model):
    content = models.CharField(max_length=10, unique=True)


class Post(models.Model):
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    photo = ProcessedImageField(
        # upload_to="media/%Y/%m/%d",
        format = 'JPEG',
        processors = [ResizeToFill(633, 633)],
        options = {'quality': 90},
    )
    content = models.TextField()
    hashtags = models.ManyToManyField(Tag, related_name='taged_posts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

posts/forms.py
from django import forms
from .models import Post, Comment, Tag

class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ('photo', 'content',)


class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ('content',)


class TagForm(forms.ModelForm):

    class Meta:
        model = Tag
        fields = '__all__'  

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404, resolve_url
from .models import Post, Comment, Tag
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST
from .forms import PostForm, CommentForm, TagForm
from accounts.models import User
from django.db.models import Count


# Create your views here.
@login_required
def index(request):
    posts = Post.objects.all().order_by('-created_at')
    followings = request.user.followings.all()
    users = User.objects.all().distinct()
    context = {
        'posts': posts,
        'followings': followings,
        'users': users,
    }
    return render(request, 'posts/index.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method=='POST':
        post_form = PostForm(request.POST, request.FILES)
        if post_form.is_valid():
            post = post_form.save(commit=False)
            post.user = request.user
            post.save()

            content = post.content.split()
            content_new = ''
            for word in content:
                if word[0]=='#':
                    if {'content': word} in Tag.objects.all().values('content'):
                        tag = Tag.objects.get(content=word)
                        post.hashtags.add(tag)                
                    else:
                        tag = Tag.objects.create(content=word)
                        post.hashtags.add(tag)                
                else:
                    content_new += word + ' '
            post.content = content_new
            post.save()

            return redirect('posts:detail', post.pk)
    else:
        post_form = PostForm()
    context = {
        'post_form': post_form,
    }
    return render(request, 'posts/create.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def detail(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    comments = post.comment_set.all()
    form = CommentForm()
    content = post.content.split()
    context = {
        'form': form,
        'post': post,
        'comments': comments,
    }
    return render(request, 'posts/detail.html', context)


@require_POST
def delete(request, post_pk):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    
    post = get_object_or_404(Post, pk=post_pk)
    if post.user==request.user:
        post.delete()
        return redirect('posts:index')
    return redirect('posts:detail', post_pk)


@login_required
@require_http_methods(['GET', 'POST'])
def update(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    if request.method=='POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        post = form.save(commit=False)
        post.user = request.user
        post.save()
        return redirect('posts:detail', post_pk)
    else:
        form = PostForm(instance=post)
    context = {
        'form': form,
    }
    return render(request, 'posts/update.html', context)


# Comments -----------------------------------------
@require_POST
def create_comment(request, post_pk):
    if not request.user.is_authenticated:
        return redirect('accounts:login')

    post = get_object_or_404(Post, pk=post_pk)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.post = post
        comment.save()
    return redirect('posts:detail', post_pk)


@require_POST
def delete_comment(request, post_pk, comment_pk):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    
    post = get_object_or_404(Post, pk=post_pk)
    comment = post.comment_set.get(pk=comment_pk)
    comment.delete()
    return redirect('posts:detail', post_pk)


# Like ---------------------------------
@require_POST
def like(request, post_pk, before):
    if not request.user.is_authenticated:
        return redirect('accounts:login')

    post = get_object_or_404(Post, pk=post_pk)
    if post.like_users.filter(username=request.user).exists():
        post.like_users.remove(request.user)
    else:
        post.like_users.add(request.user)
    
    if before=='detail':
        return redirect('posts:detail', post_pk)
    else:
        next_url = resolve_url('posts:index')
        return redirect(f'{next_url}#{before}')


# Search ------------------------------
@login_required
@require_http_methods(['GET', 'POST'])
def search(request):
    search = request.GET.get('search')
    if search[0]=='#' and Tag.objects.filter(content=search).exists():
        tag = Tag.objects.get(content=search)
        posts = tag.taged_posts.all()
        context = {
            'hashtag': search,
            'posts': posts,
        }
        return render(request, 'posts/search_result.html', context)
    elif User.objects.filter(username=search).exists():
        return redirect('accounts:profile', search)
    else:
        return render(request, 'posts/not_found.html')


@login_required
@require_http_methods(['GET', 'POST'])
def click_tag(request, hashtag):
    if Tag.objects.filter(content=hashtag).exists():
        tag = Tag.objects.get(content=hashtag)
        posts = tag.taged_posts.all()
        context = {
            'hashtag': hashtag,
            'posts': posts,
        }
        return render(request, 'posts/search_result.html', context)
    else:
        return render(request, 'posts/not_found.html')


# Close ------------------------------
# @login_required
# @require_http_methods(['GET', 'POST'])
# def close(request, post_pk, before):
#     if before=='index':
#         next_url = resolve_url('posts:index')
#         return redirect(f'{next_url}#{post_pk}')
#     else:
#         next_url = resolve_url('accounts:profile', before)
#         return redirect(f'{next_url}#{post_pk}')

posts/templates/posts/index/_left.html
{% load static %}
{% load custom_filter %}

<div class="col-sm-8 col-md-7">
  <!-- 팔로우 중인 유저 목록 -->
  <div class="border mt-3 mb-4 bg-white d-flex flex-row" style="height: 130px;">
    {% if request.user.followings.all %}
      {% for person in request.user.followings.all %}
        {% if person.post_set.all %}
          <div class="d-block text-center" style="width: 120px">
            <a href="{% url 'accounts:profile' person %}" class="text-decoration-none">
              {% if person.profile_image %}
                <img src="{{ person.profile_image.url }}" alt="{{ person.profile_image }}" class="mx-3 mt-3" style="border-radius: 50%; max-height: 55%; border-style: solid; border-color: deeppink;">
              {% else %}
                <img src="{% static 'none_profile.jpg' %}" class="mx-3 mt-3" style="border-radius: 50%; max-height: 55%; border-style: solid; border-color: deeppink;">
              {% endif %}
              <br>
              <p class="text-dark"><b>{{ person }}</b></p>
            </a>
          </div>
        {% endif %}
      {% endfor %}
    {% else %}
        <h3 class="m-5 text-center">아직 팔로우중인 친구가 없습니다.</h3>
    {% endif %}
  </div>

  <!-- 팔로우 중인 유저들의 전체 게시글 (최신글 순서대로 정렬 기능은 not yet) -->

  {% for post in posts %}
    {% if post.user in followings %}
      <div class="border mt-1 mb-5 bg-white">

        <!-- 좋아요 클릭 시 이동할 앵커(Anchor) 태그-->
        <a name="{{ post.pk }}"></a>

        <!-- 게시글 작성 유저 정보 -->
        <div class="row m-0 p-2 justify-content-between d-flex flex-row align-items-baseline">
          <div class="d-flex flex-row align-items-baseline">
            <a href="{% url 'accounts:profile' post.user %}">
              {% if post.user.profile_image %}
                <img src="{{ post.user.profile_image.url }}" alt="{{ post.user.profile_image }}" style="border-radius: 50%; width: 45px; border-style: solid; border-color: deeppink;">
              {% else %}
                <img src="{% static 'none_profile.jpg' %}" style="border-radius: 50%; width: 45px; border-style: solid; border-color: deeppink;">
              {% endif %}
            </a>
            <a class="text-decoration-none" href="{% url 'accounts:profile' post.user %}"><b class="ml-2 pl-1 my-0 text-dark">{{ post.user }}</b></a>
          </div>
          <div class="mr-2">
            <button class="btn border-0 bg-white"><h5>···</h5></button>
          </div>
        </div>

        <!-- 게시글 포스팅 이미지 -->
        {% if post.photo %}
          <a href="{% url 'posts:detail' post.pk %}">
            <img src="{{ post.photo.url }}" alt="{{ post.photo }}" style="max-width: 100%; height: auto;">      
          </a>
        {% endif %}

        <!-- 게시글 좋아요/댓글/DM 아이콘 -->
        <div class="row m-2">
          <form action="{% url 'posts:like' post.pk post.pk %}" method="POST">
            {% csrf_token %}
            {% if request.user in post.like_users.all %}
              <button class="fas fa-heart fa-2x border-0 bg-white"></button>
            {% else %}
              <button class="far fa-heart fa-2x border-0 bg-white"></button>
            {% endif %}
            <i class="far fa-comment fa-2x ml-2"></i>
            <i class="far fa-paper-plane fa-2x ml-2"></i>
          </form>
        </div>
        <p class="mx-3 my-0 py-0"><b>좋아요 {{ post.like_users.all.count }}개</b></p>

        <!-- 게시글 내용 & 댓글 관련 -->
        <div class="col pl-2 ml-2 d-none d-md-block">
          <p class="mb-1">
            <a class="text-decoration-none" href="{% url 'accounts:profile' post.user %}"><b class="mr-1 my-0 text-dark">{{ post.user }}</b></a>
            {% for word in post.content.split %}
              {{ word }}
            {% endfor %}
            <br>

            {% for tag in post.hashtags.all %}
              <a href="{% url 'posts:click_tag' tag.content %}">{{ tag.content }}</a>
            {% endfor %}
          </p>

          <p class="m-0 p-0">
            <a href="{% url 'posts:detail' post.pk %}" class="text-black-50 text-decoration-none">댓글 {{ post.comment_set.all.count }}개 모두 보기</a>
            <p class="text-black-50 pt-2" style="font-size: smaller;">{{ post.created_at|processed_timesince }} 전</p>
            
          </p>
        </div>

      </div>
    {% endif %}
  {% endfor %}
</div>

posts/templates/posts/index/_right.html
{% load static %}

<div class="col-4 my-5 d-none d-xl-block">
  <a class="text-decoration-none ml-2" href="{% url 'accounts:profile' request.user %}">
  {% if request.user.profile_image %}
    <img src="{{ request.user.profile_image.url }}" alt="{{ request.user.profile_image }}" style="border-radius: 50%; width: 65px;">
  {% else %}
    <img src="{% static 'none_profile.jpg' %}" style="width: 30%;">
  {% endif %}
  </a>
  <a class="text-decoration-none" href="{% url 'accounts:profile' request.user %}"><h5 class="display-6 d-inline ml-3 text-dark">{{ request.user }}</h5></a>
  
  <div class="row justify-content-between mt-3 align-items-baseline">
    <div class="col-7 text-black-50"><p><b>회원님을 위한 추천</b></p></div>
    <div class="col-5"><p style="font-size: small;"><a href="#" class="text-dark text-decoration-none"><b>모두 보기</b></a></p></div>
  </div>

  {% for user in users %}
    {% if user not in followings and user != request.user%}
      <div class="row align-items-center">
        <div class="col-1 mr-3">
          <a href="{% url 'accounts:profile' user %}">
            {% if user.profile_image %}
              <img src="{{ user.profile_image.url }}" alt="{{ user.profile_image }}" style="border-radius: 50%; width: 45px;">
            {% else %}
              <img src="{% static 'none_profile.jpg' %}" style="border-radius: 50%; width: 45px;">
            {% endif %}
          </a>
        </div>
        <div class="col-5 pt-2 mt-1">
          <a class="text-decoration-none" href="{% url 'accounts:profile' user %}"><b class="ml-2 pl-1 my-0 text-dark">{{ user }}</b></a>
          <p class="ml-2 pl-1 text-black-50" style="font-size: smaller;"><b>회원님을 위한 추천</b></pc>
        </div>

        <div class="col-5 pl-4 ml-2">
          <form action="" method="POST" id="follow-form" data-username="{{user}}">
            {% csrf_token %}
            <button type="submit" class="btn btn-toolbar text-primary m-0" style="font-size: smaller;"><b>팔로우</b></button>
          </form>
        </div>
      </div>
    {% endif %}
  {% endfor %}

</div>